####################
## DOMAIN ROUTES ###
####################

settings_domain_index:
    path: /domains
    methods: [GET]
    defaults:
        _controller: HarmonySettingsManagerBundle:Domain:index

settings_domain_quick_edit:
    path: /domains/{domainName}/{providerName}
    methods: [PUT]
    defaults:
        _controller: HarmonySettingsManagerBundle:Domain:quickEdit

settings_domain_copy:
    path: /domains/{domainName}/copy/{providerName}
    methods: [POST]
    defaults:
        _controller: HarmonySettingsManagerBundle:Domain:copy

settings_domain_delete:
    path: /domains/{domainName}/{providerName}
    methods: [DELETE]
    defaults:
        _controller: HarmonySettingsManagerBundle:Domain:delete
        providerName: ~

#####################
## SETTING ROUTES ###
#####################

settings_index:
    path: /{domainName}
    methods: [GET]
    defaults:
        _controller: HarmonySettingsManagerBundle:Settings:index
        domainName: default

settings_quick_edit:
    path: /{domainName}/{settingName}
    methods: [PUT]
    defaults:
        _controller: HarmonySettingsManagerBundle:Settings:quickEdit
    options:
        expose: true

settings_edit:
    path: /{domainName}/{settingName}
    methods: [GET, POST]
    defaults:
        _controller: HarmonySettingsManagerBundle:Settings:edit

settings_delete:
    path: /{domainName}/{settingName}
    methods: [DELETE]
    defaults:
        _controller: HarmonySettingsManagerBundle:Settings:delete

settings_duplicate:
    path: /{domainName}/{settingName}/duplicate/{toDomainName}
    methods: [POST]
    defaults:
        _controller: HarmonySettingsManagerBundle:Settings:duplicate
    options:
        expose: true
