services:
    _defaults:
        public: false
        autowire: false
        autoconfigure: false

    settings_manager.serializer:
        class: Symfony\Component\Serializer\Serializer
        arguments:
            $normalizers:
                - '@settings_manager.normalizer.array'
                - '@Harmony\Bundle\SettingsManagerBundle\Serializer\Normalizer\SettingNormalizer'
                - '@Harmony\Bundle\SettingsManagerBundle\Serializer\Normalizer\SettingDomainNormalizer'
                - '@Harmony\Bundle\SettingsManagerBundle\Serializer\Normalizer\SettingTagNormalizer'
            $encoders:
                - '@settings_manager.encoder.json'

    settings_manager.encoder.json:
        class: Symfony\Component\Serializer\Encoder\JsonEncoder

    settings_manager.normalizer.array:
        class: Symfony\Component\Serializer\Normalizer\ArrayDenormalizer

    Harmony\Bundle\SettingsManagerBundle\Serializer\Normalizer\SettingNormalizer: ~

    Harmony\Bundle\SettingsManagerBundle\Serializer\Normalizer\SettingDomainNormalizer: ~

    Harmony\Bundle\SettingsManagerBundle\Serializer\Normalizer\SettingTagNormalizer: ~
