services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    _instanceof:
        Symfony\Component\Validator\ConstraintValidator:
            tags:
                - { name: validator.constraint_validator }

    Harmony\Bundle\SettingsManagerBundle\Validator\Constraints\UniqueSettingValidator:
        arguments:
            - '@Harmony\Bundle\SettingsManagerBundle\Settings\SettingsManager'
